In [136]:
import numpy as np
import pandas as pd
import os 

from pathlib import Path

dir = str(Path.cwd())
encodings = pd.read_csv(dir+"/encodings(catx-orix)2.csv")
print(encodings.iloc[0][0])
avg=.05276894119
for x,y in encodings.iterrows():
    if y[1] > .05276894119:
        print("good")
    else:
        print("bad")
   
                      

rand_0
bad
good
good
good
bad
bad
bad
good
good
good
bad
bad
bad
bad
bad
bad
bad
bad
good
good
good
bad
bad
good
bad
bad
bad
bad
bad
good
good
good
bad
bad
bad
good
good
good
bad
bad
bad
good
good
good
bad
bad
good
good
bad
good
bad
good
good
bad
good
good
good
bad
good
bad
good
bad
bad
bad
good
bad
bad
good
bad
good
good
good
good
good
good
good
good
bad
bad
good
good
bad
bad
good
good
good
bad
bad
good
bad
bad
bad
bad
bad
bad
bad
bad
good
bad
bad
bad
bad
good
good
good
bad
good
good
good
bad
bad
bad
good
good
bad
bad
good
bad
good
bad
good
bad
bad
good
bad
good
bad
bad
bad
bad
bad
good
bad
good
bad
good
good
good
bad
good
bad
bad
good
bad
good
bad
bad
bad
bad
bad
bad
good
good
bad
bad
good
bad
good
good
good
bad
good
good
bad
good
bad
good
good
bad
good
bad
good
bad
bad
good
good
bad
good
bad
good
bad
good
bad
bad
good
good
good
bad
good
bad
bad
good
bad
bad
good
good
bad
good
bad
bad
bad
good
bad
good
good
bad
bad
bad
good
bad
good
bad
bad
bad
bad
bad
good
good
bad
good
good
bad
bad

In [98]:
adjs = np.load(dir+"/adjs.npy", allow_pickle=True).item()
for x in adjs:
    print(adjs[x])

[[0 0 0 ... 0 1 0]
 [0 1 1 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 1 0 0]]
[[1 0 0 ... 0 0 1]
 [1 0 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[[0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 ...
 [1 0 0 ... 1 0 0]
 [1 0 0 ... 0 1 0]
 [1 0 0 ... 1 1 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 [0 0 1 ... 1 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
[[0 0 1 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 1 ... 0 1 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]
[[0 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [

In [140]:
import torch
from torch_geometric.data import Data, DataLoader


In [138]:
beg=[]
end=[]
data_list=[]
row=0
col=0
adj=0
for x in adjs:
    for line in adjs[x]:
        #print(line)
        col=0
        for num in line:
            if num == 1:
                beg.append(row)
                end.append(col)
            col+=1
        row+=1
    #print(beg)
    #print(end)
    edge_index = torch.tensor([beg, end], dtype=torch.long)
    #print(adj)
    if encodings.iloc[adj][1] > .05276894119:
        y=1
    else:
        y=0
    
    data = Data(edge_index = edge_index, y=y)
    data_list.append(data)
    beg=[]
    end=[]
    adj+=1
    
print(data_list)
    

[Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=1), Data(edge_index=[2, 480], y=1), Data(edge_index=[2, 480], y=1), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=1), Data(edge_index=[2, 480], y=1), Data(edge_index=[2, 480], y=1), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=1), Data(edge_index=[2, 480], y=1), Data(edge_index=[2, 480], y=1), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=1), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=0), Data(edge_index=[2, 480], y=1), Data(edge_index=[2, 480], y=1), Data(ed

In [142]:
loader = DataLoader(data_list, batch_size=32)
print(type(data_list))

<class 'list'>


In [144]:
from torch_geometric.datasets import Planetoid
import torch
import torch.nn.functional as F
from torch_geometric.nn import MessagePassing
from torch_geometric.utils import add_self_loops, degree
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt


class GCNConv(MessagePassing):
    def __init__(self, in_channels, out_channels):
        super(GCNConv, self).__init__(aggr='add')  # "Add" aggregation
        self.lin = torch.nn.Linear(in_channels, out_channels)

    def forward(self, x, edge_index):
        # Step 1: Add self-loops
        edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))

        # Step 2: Multiply with weights
        x = self.lin(x)

        # Step 3: Calculate the normalization
        row, col = edge_index
        deg = degree(row, x.size(0), dtype=x.dtype)
        deg_inv_sqrt = deg.pow(-0.5)
        norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]

        # Step 4: Propagate the embeddings to the next layer
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x,
                              norm=norm)

    def message(self, x_j, norm):
        # Normalize node features.
        return norm.view(-1, 1) * x_j


class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        #self.conv1 = GCNConv(dataset.num_node_features, 16)
        self.conv1 = GCNConv(16, 2)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        #x = self.conv2(x, edge_index)

        return F.log_softmax(x, dim=1)


def test(data, train=True):
    model.eval()

    correct = 0
    pred = model(data).max(dim=1)[1]

    if train:
        correct += pred[data.train_mask].eq(data.y[data.train_mask]).sum().item()
        return correct / (len(data.y[data.train_mask]))
    else:
        correct += pred[data.test_mask].eq(data.y[data.test_mask]).sum().item()
        return correct / (len(data.y[data.test_mask]))


def train(data, plot=False):
    train_accuracies, test_accuracies = list(), list()
    for epoch in range(100):
            model.train()
            optimizer.zero_grad()
            out = model(data)
            loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
            loss.backward()
            optimizer.step()

            train_acc = test(data)
            test_acc = test(data, train=False)

            train_accuracies.append(train_acc)
            test_accuracies.append(test_acc)
            print('Epoch: {:03d}, Loss: {:.5f}, Train Acc: {:.5f}, Test Acc: {:.5f}'.
                  format(epoch, loss, train_acc, test_acc))

    if plot:
        plt.plot(train_accuracies, label="Train accuracy")
        plt.plot(test_accuracies, label="Validation accuracy")
        plt.xlabel("# Epoch")
        plt.ylabel("Accuracy")
        plt.legend(loc='upper right')
        plt.show()


if __name__ == "__main__":
    #dataset = Planetoid(root='/tmp/Cora', name='Cora')
    #print(type(dataset))
    #print(dataset.num_classes)
    #print(dataset.num_node_features)
    
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = Net().to(device)
    
    for data in loader:
        data = data.to(device)
        optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
        output = train(data)
        print(output)
        
    

#     device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
#     model = Net(dataset).to(device)
#     data = dataset[0].to(device)
#     optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

#     train(data, plot=True)

AttributeError: 'NoneType' object has no attribute 'size'