In [2]:
import numpy as np
import pandas as pd
import os 
import os.path as osp
import random
import torch
import torch.nn.functional as F
from torch_geometric.datasets import Planetoid
import torch_geometric.transforms as T
from torch_geometric.nn import GCNConv, ChebConv  # noqa
from pathlib import Path
from torch_geometric.data import Data

dir = str(Path.cwd())
encodings = pd.read_csv(dir+"/encodings(catx-orix)2.csv")
print(encodings.iloc[0][0])
#average encoding score of the graphs below
avg=.05276894119
adjs = np.load(dir+"/adjs.npy", allow_pickle=True).item()   
                      

rand_0


In [10]:
beg=[]
end=[]
data_list=[]
row=0
col=0
adj=0

x = torch.Tensor(np.zeros((1000,100))).to('cpu')
x=x+5
print(x)

#
# labels graph 1 if above average, 0 if below average
y = []
for ei, _ in enumerate(adjs):
    if encodings.iloc[ei][1] > .05276894119:
        y.append(0)
    else:
        y.append(1)
y = np.array(y)
y = torch.Tensor(y).to('cpu')

# iterates through each graph adjacency matrix, converts graph into 
# COO format as described in pytorch geom documentation. this is edge_index
# x contains the feature matrix for each node in the graph
# y is the graph label (0 or 1)
for adj_i in adjs:
    row=0
    adj_m = adjs[adj_i]
    nn, mm = adj_m.shape
    full_adj = np.vstack([np.hstack([np.zeros((nn, nn)), adj_m]), np.hstack([adj_m.T, np.zeros((mm, mm))])]) #reshape 100x100
    for line in full_adj:
        #print(line)
        col=0
        for num in line:
            if num == 1:
                beg.append(row)
                end.append(col)
            col+=1
        row+=1
    edge_index = torch.tensor([beg, end], dtype=torch.long)
    #print(edge_index)
    data = Data(edge_index = edge_index, x=x, y=y)
    #print(data.y)
    data.num_nodes=100
    data_list.append(data)
    beg=[]
    end=[]
    adj+=1
#print(data_list)

tensor([[5., 5., 5.,  ..., 5., 5., 5.],
        [5., 5., 5.,  ..., 5., 5., 5.],
        [5., 5., 5.,  ..., 5., 5., 5.],
        ...,
        [5., 5., 5.,  ..., 5., 5., 5.],
        [5., 5., 5.,  ..., 5., 5., 5.],
        [5., 5., 5.,  ..., 5., 5., 5.]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [67, 70, 78,  ..., 34, 51, 58]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 68, 73,  ..., 30, 32, 54]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 64, 66,  ..., 43, 44, 45]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [65, 66, 70,  ..., 48, 51, 55]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [64, 76, 86,  ..., 50, 57, 58]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [66, 71, 79,  ..., 39, 46, 47]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 67, 68,  ..., 49, 51, 55]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 64, 65,  ..., 50, 53, 57]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 63, 67,  ..., 50, 51, 57]])
tensor([[ 0,  0, 

tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 63, 64,  ..., 50, 53, 57]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 70, 76,  ..., 42, 43, 50]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [65, 69, 75,  ..., 50, 52, 54]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 63, 74,  ..., 41, 49, 52]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 61, 66,  ..., 52, 58, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [63, 65, 72,  ..., 45, 49, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 74, 78,  ..., 52, 54, 58]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [67, 70, 71,  ..., 29, 33, 50]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [67, 69, 70,  ..., 49, 50, 56]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 64, 69,  ..., 37, 41, 43]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 66, 69,  ..., 53, 57, 58]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 63, 77,  ..., 55, 57, 59]])
tensor([[ 0,  0,  0,  ..., 9

tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 62, 68,  ..., 41, 47, 48]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 72, 73,  ..., 57, 58, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 64, 67,  ..., 52, 57, 58]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [64, 66, 67,  ..., 57, 58, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 64, 65,  ..., 43, 44, 48]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 63, 66,  ..., 16, 27, 30]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 66, 71,  ..., 41, 45, 49]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [65, 69, 76,  ..., 53, 54, 58]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [68, 70, 73,  ..., 34, 36, 45]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [66, 67, 69,  ..., 32, 42, 50]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 61, 69,  ..., 53, 54, 55]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 63, 67,  ..., 39, 43, 59]])
tensor([[ 0,  0,  0,  ..., 9

tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [75, 81, 87,  ..., 55, 56, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 67, 81,  ..., 49, 54, 58]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [66, 68, 71,  ..., 50, 54, 56]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [65, 66, 80,  ..., 44, 45, 57]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 61, 71,  ..., 41, 45, 49]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 64, 66,  ..., 37, 54, 56]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [65, 69, 70,  ..., 50, 58, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [71, 78, 86,  ..., 52, 53, 56]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 70, 72,  ..., 32, 41, 49]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 67, 73,  ..., 53, 57, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 63, 73,  ..., 45, 50, 56]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 69, 71,  ..., 44, 49, 52]])
tensor([[ 0,  0,  0,  ..., 9

tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [63, 73, 77,  ..., 53, 55, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [64, 68, 71,  ..., 53, 55, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [64, 70, 77,  ..., 54, 55, 56]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [63, 65, 67,  ..., 25, 46, 49]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [64, 66, 68,  ..., 48, 51, 55]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [70, 73, 78,  ..., 27, 40, 45]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 65, 77,  ..., 34, 41, 44]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 66, 67,  ..., 46, 51, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 69, 76,  ..., 52, 56, 58]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 61, 68,  ..., 46, 51, 56]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [73, 77, 79,  ..., 52, 54, 55]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 65, 75,  ..., 41, 43, 45]])
tensor([[ 0,  0,  0,  ..., 9

tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [65, 71, 72,  ..., 54, 55, 58]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 61, 65,  ..., 51, 55, 57]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [63, 69, 72,  ..., 47, 49, 52]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 62, 66,  ..., 42, 52, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 74, 80,  ..., 54, 55, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 63, 80,  ..., 39, 41, 46]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [65, 69, 76,  ..., 44, 46, 58]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 65, 72,  ..., 44, 46, 48]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 63, 64,  ..., 49, 51, 54]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 64, 70,  ..., 45, 57, 58]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [72, 79, 85,  ..., 50, 52, 55]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [64, 66, 67,  ..., 54, 55, 59]])
tensor([[ 0,  0,  0,  ..., 9

tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [67, 70, 75,  ..., 52, 58, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 64, 67,  ..., 44, 55, 57]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 70, 74,  ..., 46, 56, 58]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [63, 64, 68,  ..., 53, 54, 55]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [66, 73, 77,  ..., 49, 50, 54]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 73, 75,  ..., 54, 56, 57]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [66, 77, 79,  ..., 40, 54, 57]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [68, 69, 70,  ..., 49, 50, 57]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [67, 68, 70,  ..., 44, 51, 55]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [70, 71, 73,  ..., 49, 53, 57]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 62, 64,  ..., 52, 53, 57]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 77, 87,  ..., 44, 47, 56]])
tensor([[ 0,  0,  0,  ..., 9

tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [67, 68, 72,  ..., 45, 47, 56]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 61, 63,  ..., 42, 43, 53]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 69, 71,  ..., 38, 42, 53]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [66, 81, 82,  ..., 49, 57, 58]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [65, 69, 73,  ..., 49, 52, 56]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [61, 65, 73,  ..., 39, 41, 46]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [64, 65, 70,  ..., 33, 35, 52]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 73, 76,  ..., 52, 54, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 62, 66,  ..., 54, 58, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [63, 64, 69,  ..., 49, 51, 57]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [62, 64, 71,  ..., 56, 57, 59]])
tensor([[ 0,  0,  0,  ..., 99, 99, 99],
        [60, 61, 67,  ..., 50, 53, 59]])
tensor([[ 0,  0,  0,  ..., 9

In [5]:
#Graph Convolutional Network classification model as adapted from he
NUM_ITER = 1000

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1=GCNConv(100, 16, cached=True)
        self.conv2 = GCNConv(16, 2, cached=True)

    def forward(self, data):
        #print(data.x.shape, data.edge_index.shape)
        x, edge_index = data.x, data.edge_index
        #edge_index = data.edge_index
        #x = F.relu(self.conv1(edge_index))
        #x = F.dropout(x, training=self.training)
        x = F.relu(self.conv1(x, edge_index))
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)
        
       # x=self.conv1(edge_index)
        return F.log_softmax(x, dim=1)



def train():
    model.train()
    optimizer.zero_grad()
    F.nll_loss(model(data).reshape(1000,2), data.y.long()).backward()
    optimizer.step()


@torch.no_grad()
def test(data):
    model.eval()
    logits, accs = model(data).reshape(1000,2), []
    pred = logits.max(1)[1]
    print(data.y)
    print(pred)
    acc=pred.eq(data.y).sum().item()
    return acc


device = torch.device('cpu')
model = Net().to(device)
for i in range(NUM_ITER):
    # Choose a random graph from the list to use
    data = data_list[random.randint(0,999)].to(device)
    #optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
    optimizer = torch.optim.Adam([
        dict(params=model.conv1.parameters(), weight_decay=5e-4),
    ], lr=0.01) 
    best_val_acc = test_acc = 0
    train()

ans = test(data)
print(ans)



tensor([1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0.,
        0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1.,
        0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1.,
        1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0.,
        0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0.,
        1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1.,
        0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0.,
        0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0.,
        1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0.,
        1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
        0., 0., 1., 0., 0., 1., 1., 0., 